package:
  name: scanpdf
  version: "0.0.0"

source:
# this is used for build from git hub
  git_rev: 0.0.0
  git_url: https://github.com/mjirik/scanpdf.git

# this is used for pypi
  # fn: io3d-1.0.30.tar.gz
  # url: https://pypi.python.org/packages/source/i/io3d/io3d-1.0.30.tar.gz
  # md5: a3ce512c4c97ac2410e6dcc96a801bd8
#  patches:
   # List any patch files here
   # - fix.patch

build:
  ignore_prefix_files:
    - devel
    - examples
  
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - scanpdf = scanpdf:main
    #
    # Would create an entry point called io3d that calls scanpdf.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python=3
    - numpy
    - setuptools
    - scikit-image
    - pyqt=5
    - ruamel.yaml
    - pyqtgraph
    - tesseract
    - tesserocr

  run:
    - python=3
    - numpy
    - scikit-image
    - pyqt=5
    - ruamel.yaml
    - pyqtgraph
    - tesseract
    - tesserocr
    # - numpy
    # - pyqt 4.11.*

test:
  # Python imports
  imports:
    - scanpdf

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mjirik/scanpdf
  license: BSD License
  summary: 'Make PDFs from directory with scanned documents'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
